# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('views', models.IntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('PR', 'In Progress'), ('PL', 'In Planning'), ('C', 'Completed'), ('W', 'Waiting to be Funded'), ('R', 'Recently Submitted')], default='R', max_length=2)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
