# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('strap', models.CharField(default='', max_length=254)),
                ('description', models.TextField(default='')),
                ('upvotes', models.IntegerField(default='0')),
                ('tag', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('target', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('tribute', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img')),
                ('status', models.CharField(choices=[('PR', 'In Progress'), ('PL', 'In Planning'), ('C', 'Completed'), ('W', 'Waiting to be Funded')], default='W', max_length=2)),
            ],
        ),
    ]
