# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
