# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_product_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
