# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_product_tribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
    ]
