# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strap',
            field=models.CharField(default='', max_length=254),
        ),
    ]
