# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_product_strap'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PR', 'In Progress'), ('PL', 'In Planning'), ('C', 'Completed'), ('W', 'Waiting to be Funded')], default='W', max_length=2),
        ),
    ]
